language: rust

cache:
  cargo: true
  apt: true
  directories:
    - $HOME/lib
    - $HOME/include

rust:
  - stable
  - beta

addons:
  apt:
    packages:
      # Cargo coverage dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

install:
  - cargo install cargo-travis || echo "Cargo travis is already installed!"
  - export PATH=$HOME/.cargo/bin:$PATH

before_script:
  - ./bin/build-dev

script:
  - ./bin/test

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/ --all
  fi
