language: rust

cache:
  cargo: true
  apt: true
  directories:
    - $HOME/lib
    - $HOME/include

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - export PATH=$HOME/.cargo/bin:$PATH

before_script:
  - ./bin/build-dev

script:
  - ./bin/test
